# Generated by Django 4.1.3 on 2022-11-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Mobile_No', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Account_status', models.CharField(max_length=200)),
            ],
        ),
    ]
